version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - app_network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

      # Creating volumes for Elasticsearch data persistence
      # This is important to ensure that data is not lost when the container is stopped or removed.

  backend:
    build: ./backend
    container_name: fastapi_backend
    depends_on:
      - elasticsearch
    networks:
      - app_network
    ports:
      - "9567:9567"

  frontend:
    build: ./frontend
    container_name: fastapi_frontend
    depends_on:
      - backend
    networks:
      - app_network
    ports:
      - "9567:9567"

networks:
  app_network:

volumes:
  elasticsearch_data:
